require:
  - solidus_dev_support/rubocop

inherit_gem:
  solidus_dev_support: .rubocop.yml

AllCops:
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Rails/ApplicationJob:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
    - spec/**/*

RSpec/MultipleExpectations:
  # Default is 1
  Max: 5

RSpec/NestedGroups:
  # Default is 3
  Max: 6
