require:
  - solidus_dev_support/rubocop

Metrics/LineLength:
  Enabled: true
  Max: 120

Rails/ApplicationJob:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
    - spec/**/*

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  # Default is 1
  Max: 5

RSpec/NestedGroups:
  # Default is 3
  Max: 6
